# Generated by Django 4.0.2 on 2022-03-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('biography', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age_range', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('price', models.FloatField()),
                ('discount', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='uploads/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('screen', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=20, unique=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('screen', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('kr', 'Korean'), ('cn', 'Chinese')], max_length=3)),
                ('number_of_pages', models.IntegerField()),
                ('summary', models.TextField(max_length=500)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('authors', models.ManyToManyField(to='store.Author')),
                ('genres', models.ManyToManyField(to='store.Genre')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.publisher')),
            ],
        ),
    ]
