# Generated by Django 3.2.6 on 2022-03-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220318_0206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobilePhone',
        ),
    ]
