# Generated by Django 3.2.6 on 2022-03-26 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_mobilephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('screen', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
            ],
        ),
    ]
