# Generated by Django 4.0.2 on 2022-03-01 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_type_laptop_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('kr', 'Korean'), ('cn', 'Chinese')], default='vi', max_length=3),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
