# Generated by Django 4.0.2 on 2022-03-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_publisher_delete_book_alter_category_age_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('biography', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('kr', 'Korean'), ('cn', 'Chinese')], max_length=3)),
                ('number_of_pages', models.IntegerField()),
                ('isbn', models.CharField(max_length=20)),
            ],
        ),
    ]
