# Generated by Django 4.0.2 on 2022-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(default='summary', max_length=500),
        ),
    ]
