# Generated by Django 4.0.2 on 2022-03-01 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_book_author_remove_book_category_book_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('price', models.FloatField()),
                ('discount', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='uploads/images/book_items/')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stores.book')),
            ],
        ),
    ]
