# Generated by Django 4.0.2 on 2022-03-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_bookitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='image',
            field=models.ImageField(upload_to='upload/images/book_items/'),
        ),
    ]
