# Generated by Django 4.0.2 on 2022-03-02 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_alter_bookitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobilephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('screen', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mobilephone_manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mobilephone_item',
            fields=[
                ('mobilephone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stores.mobilephone')),
                ('price', models.FloatField()),
                ('discount', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='uploads/images/mobilephone_items/')),
            ],
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='mobilephone_manufacture',
            field=models.ManyToManyField(to='stores.Mobilephone_manufacture'),
        ),
    ]
