# Generated by Django 4.0.2 on 2022-03-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_alter_bookitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ram', models.IntegerField()),
                ('screen', models.TextField(max_length=500)),
                ('model', models.TextField(max_length=20, unique=True)),
            ],
        ),
    ]
