# Generated by Django 4.0.2 on 2022-03-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopItem',
            fields=[
                ('laptop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stores.laptop')),
                ('price', models.FloatField()),
                ('discount', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='uploads/images/book_items/')),
            ],
        ),
    ]
