# Generated by Django 4.0.2 on 2022-03-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_mobilephone_mobilephone_manufacture_mobilephone_item_and_more'),
        ('stores', '0017_manufacture_laptop_manufacture'),
    ]

    operations = [
    ]
