# Generated by Django 4.0.2 on 2022-03-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_merge_20220302_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClothesManufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhoneItem',
            fields=[
                ('mobile_phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stores.mobilephone')),
                ('price', models.FloatField()),
                ('discount', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='uploads/images/mobile_phone_items/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Manufacture',
            new_name='LaptopManufacture',
        ),
        migrations.RenameModel(
            old_name='Mobilephone_manufacture',
            new_name='MobilePhoneManufacture',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='manufacture',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='mobilephone_manufacture',
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptop_manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.laptopmanufacture'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='mobile_phone_manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.mobilephonemanufacture'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='laptopitem',
            name='image',
            field=models.ImageField(upload_to='uploads/images/laptop_items/'),
        ),
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('clothes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stores.clothes')),
                ('price', models.FloatField()),
                ('discount', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to='uploads/images/clothes_items/')),
            ],
        ),
        migrations.DeleteModel(
            name='Mobilephone_item',
        ),
        migrations.AddField(
            model_name='clothes',
            name='clothes_manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.clothesmanufacture'),
        ),
    ]
