# Generated by Django 4.0.2 on 2022-03-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_clothes_clothesmanufacture_mobilephoneitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='categories',
        ),
    ]
